# -*- coding: utf-8 -*-
# Created by Gustavo Del Negro <gustavodelnegro@gmail.com> on 14/09/16.

"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

from ._base import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k@f9+qfao*hwbtxleg&^&balf3e8(@r468ve-f&85le5#eg0xw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'admin_portfolio',                      # Or path to database file if using sqlite3.
        'USER': 'admin_portfolio',
        'PASSWORD': 'U4FPjtyWvqGkrW72',
        'HOST': 'localhost',                      # Empty for localhost through domain sockets or           '127.0.0.1' for localhost through TCP.
        'PORT': '',                      # Set to empty string for default.
    }
}

STATIC_ROOT = "/srv/portfolio/src/static/"
ENV = "PROD"

EMAIL_HOST = 'gustavodelnegro.com.br'
EMAIL_HOST_USER = 'contato@gdelnegro.com.br'
EMAIL_HOST_PASSWORD = 'gutinho17'
EMAIL_PORT = 25
EMAIL_USE_TLS = True