# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('site', models.URLField(verbose_name='Site')),
                ('proeficiency', models.PositiveIntegerField(verbose_name='Proficiency')),
                ('sql', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Databases',
                'verbose_name': 'Database',
            },
        ),
        migrations.CreateModel(
            name='Frameworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('site', models.URLField(verbose_name='Site')),
                ('proeficiency', models.PositiveIntegerField(verbose_name='Proficiency')),
            ],
            options={
                'verbose_name_plural': 'Frameworks',
                'verbose_name': 'Framework',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('image_string', models.TextField(verbose_name='Image')),
                ('mimetype', models.TextField()),
                ('extension', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Images',
                'verbose_name': 'Image',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('site', models.URLField(verbose_name='Site')),
                ('proeficiency', models.PositiveIntegerField(verbose_name='Proficiency')),
                ('logo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Image')),
            ],
            options={
                'verbose_name_plural': 'Progamming Languages',
                'verbose_name': 'Progamming Language',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('description', models.TextField(verbose_name='Description')),
                ('database', models.ManyToManyField(to='portfolio.Databases')),
                ('framework', models.ManyToManyField(to='portfolio.Frameworks')),
                ('images', models.ManyToManyField(blank=True, to='portfolio.Image')),
                ('programming_language', models.ManyToManyField(to='portfolio.ProgrammingLanguages')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'verbose_name': 'Project',
            },
        ),
        migrations.CreateModel(
            name='ProjectTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Project Types',
                'verbose_name': 'Project Type',
            },
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('site', models.URLField(verbose_name='Site')),
                ('proeficiency', models.PositiveIntegerField(verbose_name='Proficiency')),
                ('logo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Image')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'verbose_name': 'Technology',
            },
        ),
        migrations.CreateModel(
            name='TechnologyTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('site', models.URLField(verbose_name='Site')),
                ('proeficiency', models.PositiveIntegerField(verbose_name='Proficiency')),
                ('logo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Image')),
            ],
            options={
                'verbose_name_plural': 'Technology Types',
                'verbose_name': 'Technology Type',
            },
        ),
        migrations.CreateModel(
            name='WebServers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('site', models.URLField(verbose_name='Site')),
                ('proeficiency', models.PositiveIntegerField(verbose_name='Proficiency')),
                ('logo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Image')),
            ],
            options={
                'verbose_name_plural': 'Web servers',
                'verbose_name': 'Web server',
            },
        ),
        migrations.AddField(
            model_name='technologies',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.TechnologyTypes'),
        ),
        migrations.AddField(
            model_name='projects',
            name='techonology',
            field=models.ManyToManyField(to='portfolio.Technologies'),
        ),
        migrations.AddField(
            model_name='projects',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.ProjectTypes'),
        ),
        migrations.AddField(
            model_name='projects',
            name='webserver',
            field=models.ManyToManyField(to='portfolio.WebServers'),
        ),
        migrations.AddField(
            model_name='frameworks',
            name='language',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.ProgrammingLanguages'),
        ),
        migrations.AddField(
            model_name='frameworks',
            name='logo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Image'),
        ),
        migrations.AddField(
            model_name='databases',
            name='logo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Image'),
        ),
    ]
