# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20160516_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='en_description',
            field=models.TextField(null=True, verbose_name='En Description'),
        ),
        migrations.AddField(
            model_name='projects',
            name='en_name',
            field=models.CharField(max_length=100, null=True, verbose_name='En Project Name'),
        ),
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='projecttypes',
            name='_description',
            field=models.TextField(blank=True, null=True, verbose_name='En Description'),
        ),
        migrations.AddField(
            model_name='projecttypes',
            name='_name',
            field=models.CharField(max_length=100, null=True, verbose_name='En Name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
