# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20160516_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttypes',
            old_name='_description',
            new_name='en_description',
        ),
        migrations.RenameField(
            model_name='projecttypes',
            old_name='_name',
            new_name='en_name',
        ),
    ]
