# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20160516_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('ED', 'Education'), ('XP', 'Experience'), ('AW', 'Awards')], default='ED', max_length=2)),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('en_title', models.CharField(max_length=100, null=True, verbose_name='En Title')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('en_description', models.TextField(null=True, verbose_name='En Description')),
                ('where', models.TextField(verbose_name='Where')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
