# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20160523_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases',
            name='logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Image'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Image'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Image'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Image'),
        ),
        migrations.AlterField(
            model_name='technologytypes',
            name='logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Image'),
        ),
        migrations.AlterField(
            model_name='webservers',
            name='logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Image'),
        ),
    ]
