# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20160523_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='technologytypes',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='webservers',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
    ]
