# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20160523_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.TechnologyTypes'),
        ),
    ]
