# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20160523_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='database',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.Databases'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='framework',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.Frameworks'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='techonology',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.Technologies'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='webserver',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.WebServers'),
        ),
    ]
