# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 11:29
from __future__ import unicode_literals

from django.db import migrations


def load_data(apps, schema_editor):
    translation = apps.get_model("portfolio", "TranslationType")
    translation(tag='MDL', text_pt_br="Modelo", text_en="Model", has_auxiliary_text=True, auxiliary_tag="TTP").save()
    translation(tag='MTA', text_pt_br="Meta", text_en="Meta", has_auxiliary_text=True, auxiliary_tag="MTP").save()
    translation(tag='GEN', text_pt_br="Texto", text_en="General Text", has_auxiliary_text="", auxiliary_tag="GTP").save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
