# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 11:33
from __future__ import unicode_literals

from django.db import migrations
from portfolio.models import TranslationType, Translation


def __load_data(**kwargs):
    try:
        mdl = Translation.objects.get(tag=kwargs['tag'])
    except Translation.DoesNotExist:
        mdl = Translation()
    except Exception as err:
        raise err
    for k, v in kwargs.items():
        if k == "type":
            try:
                translation_type = TranslationType.objects.get(tag=v)
            except TranslationType.DoesNotExist:
                translation_type = TranslationType.objects.get(tooltip_tag=v)
            setattr(mdl, k, translation_type)
        else:
            setattr(mdl, k, v)
    mdl.save()


def load_data(apps, schema_editor):
    __load_data(tag='TTP001', type='TTP', text_pt_br="Data da criação do registro",
                text_en="Date of the record creation")
    __load_data(tag='TTP002', type='TTP', text_pt_br="Data da atualização do registro",
                text_en="Date of the record update")
    __load_data(tag='TTP003', type='TTP', text_pt_br="Nome do registro", text_en="Record name")
    __load_data(tag='TTP004', type='TTP', text_pt_br="Descrição do Registro", text_en="Record descriptio")
    __load_data(tag='TTP005', type='TTP', text_pt_br="Título da imagem", text_en="Image title")
    __load_data(tag='TTP006', type='TTP', text_pt_br="Dado Binário da Imagem", text_en="Image binary data")
    __load_data(tag='TTP007', type='TTP', text_pt_br="Tipo do arquivo", text_en="Image type")
    __load_data(tag='TTP008', type='TTP', text_pt_br="Extensão da imagem", text_en="Image extension")
    __load_data(tag='MTP001', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP002', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='TTP009', type='TTP', text_pt_br="Site", text_en="Site")
    __load_data(tag='TTP010', type='TTP', text_pt_br="Proeficiência", text_en="Proficiency")
    __load_data(tag='TTP011', type='TTP', text_pt_br="Logo", text_en="Logo")
    __load_data(tag='MTP003', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP004', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP005', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP006', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='TTP012', type='TTP', text_pt_br="Linguagem de programação do framework",
                text_en="Framework's programming language")
    __load_data(tag='MTP007', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP008', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='TTP013', type='TTP', text_pt_br="Se a base de dados é do tipo SQL",
                text_en="If the database is SQL")
    __load_data(tag='MTP009', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP010', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP011', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP012', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP013', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP014', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='TTP014', type='TTP', text_pt_br="Tipo de tecnologia", text_en="Tipo de tecnologia")
    __load_data(tag='MTP015', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP016', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='TTP015', type='TTP', text_pt_br="Tipo de projeto", text_en="Tipo de projeto")
    __load_data(tag='TTP016', type='TTP', text_pt_br="Linguagens de programação utilizadas",
                text_en="Programming languages used in the project")
    __load_data(tag='TTP017', type='TTP', text_pt_br="Frameworks utilizados no projeto",
                text_en="Frameworks used in the project")
    __load_data(tag='TTP018', type='TTP', text_pt_br="Bases de dados utilizadas no projeto",
                text_en="Databases used in the project")
    __load_data(tag='TTP019', type='TTP', text_pt_br="Tecnologias utilizadas no projeto",
                text_en="Technologies used in the project")
    __load_data(tag='TTP020', type='TTP', text_pt_br="Servidores web utilizados no projeto",
                text_en="Webservers used in the project")
    __load_data(tag='TTP021', type='TTP', text_pt_br="Imagens do projeto", text_en="Project's images")
    __load_data(tag='MTP017', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP018', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='TTP022', type='TTP', text_pt_br="Educação", text_en="Education")
    __load_data(tag='TTP023', type='TTP', text_pt_br="Experiência", text_en="Experience")
    __load_data(tag='TTP024', type='TTP', text_pt_br="Prêmios", text_en="Awards")
    __load_data(tag='TTP025', type='TTP', text_pt_br="Tipo de experiência", text_en="Experience type")
    __load_data(tag='TTP026', type='TTP', text_pt_br="Mês de início", text_en="Start month")
    __load_data(tag='TTP027', type='TTP', text_pt_br="Ano de início", text_en="Start year")
    __load_data(tag='TTP028', type='TTP', text_pt_br="Mês de término", text_en="End month")
    __load_data(tag='TTP029', type='TTP', text_pt_br="Ano de término", text_en="End year")
    __load_data(tag='TTP030', type='TTP', text_pt_br="Cargo", text_en="Title")
    __load_data(tag='TTP031', type='TTP', text_pt_br="Localização", text_en="Location")
    __load_data(tag='MTP019', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP020', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='MTP021', type='MTP', text_pt_br="-", text_en="-")
    __load_data(tag='TTP032', type='TTP', text_pt_br="-", text_en="-")
    __load_data(tag='TTP033', type='TTP', text_pt_br="-", text_en="-")
    __load_data(tag='TTP034', type='TTP', text_pt_br="-", text_en="-")
    __load_data(tag='TTP035', type='TTP', text_pt_br="-", text_en="-")
    __load_data(tag='TTP036', type='TTP', text_pt_br="-", text_en="-")
    __load_data(tag='TTP037', type='TTP', text_pt_br="-", text_en="-")
    __load_data(tag='TTP038', type='TTP', text_pt_br="-", text_en="-")
    __load_data(tag='MDL001', type='MDL', text_pt_br="Data de criação", text_en="Creation date")
    __load_data(tag='MDL002', type='MDL', text_pt_br="Data de atualização", text_en="Update date")
    __load_data(tag='MDL003', type='MDL', text_pt_br="Nome", text_en="Name")
    __load_data(tag='MDL004', type='MDL', text_pt_br="Descrição", text_en="Description")
    __load_data(tag='MDL005', type='MDL', text_pt_br="Título", text_en="Title")
    __load_data(tag='MDL006', type='MDL', text_pt_br="Dado binário", text_en="Binary data")
    __load_data(tag='MDL007', type='MDL', text_pt_br="Tipo MIME", text_en="MIME type")
    __load_data(tag='MDL008', type='MDL', text_pt_br="Extensão", text_en="Extension")
    __load_data(tag='MTA001', type='MTA', text_pt_br="Imagem", text_en="Image")
    __load_data(tag='MTA002', type='MTA', text_pt_br="Imagens", text_en="Images")
    __load_data(tag='MDL009', type='MDL', text_pt_br="Site", text_en="Site")
    __load_data(tag='MDL010', type='MDL', text_pt_br="Proeficiência", text_en="Proficiency")
    __load_data(tag='MDL011', type='MDL', text_pt_br="Logo", text_en="Logo")
    __load_data(tag='MTA003', type='MTA', text_pt_br="Linguagem de programação",
                text_en="Linguagens de programação")
    __load_data(tag='MTA004', type='MTA', text_pt_br="Linguagens de programação", text_en="Programming languages")
    __load_data(tag='MTA005', type='MTA', text_pt_br="Framework", text_en="Framework")
    __load_data(tag='MTA006', type='MTA', text_pt_br="Frameworks", text_en="Frameworks")
    __load_data(tag='MDL012', type='MDL', text_pt_br="Linguagem de programação do framework",
                text_en="Framework's programming language")
    __load_data(tag='MTA007', type='MTA', text_pt_br="Base de dados", text_en="Database")
    __load_data(tag='MTA008', type='MTA', text_pt_br="Bases de dados", text_en="Databases")
    __load_data(tag='MDL013', type='MDL', text_pt_br="SQL", text_en="SQL")
    __load_data(tag='MTA009', type='MTA', text_pt_br="Servidor web", text_en="Webserver")
    __load_data(tag='MTA010', type='MTA', text_pt_br="Servidores web", text_en="Webservers")
    __load_data(tag='MTA011', type='MTA', text_pt_br="Tipo de tecnologia", text_en="Technology type")
    __load_data(tag='MTA012', type='MTA', text_pt_br="Tipos de tecnologia", text_en="Technology types")
    __load_data(tag='MTA013', type='MTA', text_pt_br="Tecnologia", text_en="Technology")
    __load_data(tag='MTA014', type='MTA', text_pt_br="Tecnologias", text_en="Technologies")
    __load_data(tag='MDL014', type='MDL', text_pt_br="Tipo de tecnologia", text_en="Technology type")
    __load_data(tag='MTA015', type='MTA', text_pt_br="Tipo de projeto", text_en="Project type")
    __load_data(tag='MTA016', type='MTA', text_pt_br="Tipos de projeto", text_en="Projects types")
    __load_data(tag='MDL015', type='MDL', text_pt_br="Tipo de projeto", text_en="Project type")
    __load_data(tag='MDL016', type='MDL', text_pt_br="Linguagem de programação utilizada",
                text_en="Programming language used")
    __load_data(tag='MDL017', type='MDL', text_pt_br="Frameworks utilizado", text_en="Framework used")
    __load_data(tag='MDL018', type='MDL', text_pt_br="Base de dados utilizada", text_en="Database used")
    __load_data(tag='MDL019', type='MDL', text_pt_br="Tecnologia utilizada", text_en="Technology used")
    __load_data(tag='MDL020', type='MDL', text_pt_br="Servidor web utilizado", text_en="Webserver used")
    __load_data(tag='MDL021', type='MDL', text_pt_br="Imagens do projeto", text_en="Project's images")
    __load_data(tag='MTA017', type='MTA', text_pt_br="Projeto", text_en="Project")
    __load_data(tag='MTA018', type='MTA', text_pt_br="Projetos", text_en="Projects")
    __load_data(tag='MDL022', type='MDL', text_pt_br="Educação", text_en="Education")
    __load_data(tag='MDL023', type='MDL', text_pt_br="Experiência", text_en="Experience")
    __load_data(tag='MDL024', type='MDL', text_pt_br="Prêmios", text_en="Awards")
    __load_data(tag='MDL025', type='MDL', text_pt_br="Tipo de experiência", text_en="Experience type")
    __load_data(tag='MDL026', type='MDL', text_pt_br="Mês de início", text_en="Start month")
    __load_data(tag='MDL027', type='MDL', text_pt_br="Ano de início", text_en="Start year")
    __load_data(tag='MDL028', type='MDL', text_pt_br="Mês de término", text_en="End month")
    __load_data(tag='MDL029', type='MDL', text_pt_br="Ano de término", text_en="End year")
    __load_data(tag='MDL030', type='MDL', text_pt_br="Cargo", text_en="Title")
    __load_data(tag='MDL031', type='MDL', text_pt_br="Localização", text_en="Location")
    __load_data(tag='MTA019', type='MTA', text_pt_br="Currículo", text_en="Resume")
    __load_data(tag='MTA020', type='MTA', text_pt_br="Tradução", text_en="Translation")
    __load_data(tag='MTA021', type='MTA', text_pt_br="Traduções", text_en="Translations")
    __load_data(tag='MDL032', type='MDL', text_pt_br="tag", text_en="tag")
    __load_data(tag='MDL033', type='MDL', text_pt_br="Tipo", text_en="type")
    __load_data(tag='MDL034', type='MDL', text_pt_br="Texto", text_en="Text")
    __load_data(tag='MDL035', type='MDL', text_pt_br="Ajuda de modelo", text_en="Model tooltip")
    __load_data(tag='MDL036', type='MDL', text_pt_br="Modelo", text_en="Model")
    __load_data(tag='MDL037', type='MDL', text_pt_br="Meta", text_en="Meta")
    __load_data(tag='MDL038', type='MDL', text_pt_br="Ajuda de meta", text_en="Meta tooltip")

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_translation_type_data_20160728_1129'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
