# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_translation_type_data_20160728_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='tooltip_tag',
            field=models.CharField(help_text='TTP032', max_length=20, unique=True, verbose_name='ToolTipTag'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='tooltip_text',
            field=models.TextField(help_text='TTP034', verbose_name='ToolTipText'),
        ),
    ]
