# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='text_en',
            field=models.TextField(help_text='TTP034', null=True, verbose_name='MDL034'),
        ),
        migrations.AddField(
            model_name='translation',
            name='text_pt_br',
            field=models.TextField(help_text='TTP034', null=True, verbose_name='MDL034'),
        ),
    ]
