# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20160716_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='databases',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='databases',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='databases',
            name='name_en',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='databases',
            name='name_pt_br',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='frameworks',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='frameworks',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='frameworks',
            name='name_en',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='frameworks',
            name='name_pt_br',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='programminglanguages',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='programminglanguages',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='programminglanguages',
            name='name_en',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='programminglanguages',
            name='name_pt_br',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='projects',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='projects',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='projects',
            name='name_en',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='projects',
            name='name_pt_br',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='projecttypes',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='projecttypes',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='projecttypes',
            name='name_en',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='projecttypes',
            name='name_pt_br',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='resume',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='resume',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='resume',
            name='name_en',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='resume',
            name='name_pt_br',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='technologies',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='technologies',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='technologies',
            name='name_en',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='technologies',
            name='name_pt_br',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='technologytypes',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='technologytypes',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='technologytypes',
            name='name_en',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='technologytypes',
            name='name_pt_br',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='webservers',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='webservers',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='webservers',
            name='name_en',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='webservers',
            name='name_pt_br',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
    ]
