# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_translation_initial_data_20160902_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databases',
            options={'verbose_name': 'MTA4', 'verbose_name_plural': 'MTP4'},
        ),
        migrations.AlterModelOptions(
            name='frameworks',
            options={'verbose_name': 'MTA3', 'verbose_name_plural': 'MTP3'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'MTA1', 'verbose_name_plural': 'MTP1'},
        ),
        migrations.AlterModelOptions(
            name='programminglanguages',
            options={'verbose_name': 'MTA2', 'verbose_name_plural': 'MTP2'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'MTA9', 'verbose_name_plural': 'MTP9'},
        ),
        migrations.AlterModelOptions(
            name='projecttypes',
            options={'verbose_name': 'MTA8', 'verbose_name_plural': 'MTP8'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'MTA10', 'verbose_name_plural': 'MTP10'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'MTA13', 'verbose_name_plural': 'MTP13'},
        ),
        migrations.AlterModelOptions(
            name='technologies',
            options={'verbose_name': 'MTA7', 'verbose_name_plural': 'MTP7'},
        ),
        migrations.AlterModelOptions(
            name='technologytypes',
            options={'verbose_name': 'MTA6', 'verbose_name_plural': 'MTP6'},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'verbose_name': 'MTA11', 'verbose_name_plural': 'MTP11'},
        ),
        migrations.AlterModelOptions(
            name='translationtype',
            options={'verbose_name': 'MTA12', 'verbose_name_plural': 'MTP12'},
        ),
        migrations.AlterModelOptions(
            name='webservers',
            options={'verbose_name': 'MTA5', 'verbose_name_plural': 'MTP5'},
        ),
        migrations.AlterField(
            model_name='databases',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='description',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='logo',
            field=models.OneToOneField(blank=True, help_text='TTP11', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Image', verbose_name='MDL11'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='name',
            field=models.CharField(help_text='TTP3', max_length=100, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='name_en',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='name_pt_br',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='proficiency',
            field=models.PositiveIntegerField(help_text='TTP10', verbose_name='MDL10'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='site',
            field=models.URLField(blank=True, help_text='TTP9', null=True, verbose_name='MDL9'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='sql',
            field=models.BooleanField(default=True, help_text='TTP13', verbose_name='MDL13'),
        ),
        migrations.AlterField(
            model_name='databases',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='description',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='language',
            field=models.ForeignKey(help_text='TTP12', on_delete=django.db.models.deletion.CASCADE, to='portfolio.ProgrammingLanguages', verbose_name='MDL12'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='logo',
            field=models.OneToOneField(blank=True, help_text='TTP11', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Image', verbose_name='MDL11'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='name',
            field=models.CharField(help_text='TTP3', max_length=100, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='name_en',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='name_pt_br',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='proficiency',
            field=models.PositiveIntegerField(help_text='TTP10', verbose_name='MDL10'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='site',
            field=models.URLField(blank=True, help_text='TTP9', null=True, verbose_name='MDL9'),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='image',
            name='extension',
            field=models.TextField(help_text='TTP8', verbose_name='MDL8'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_string',
            field=models.TextField(help_text='TTP6', verbose_name='MDL6'),
        ),
        migrations.AlterField(
            model_name='image',
            name='mimetype',
            field=models.TextField(help_text='TTP7', verbose_name='MDL7'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(help_text='TTP3', max_length=100, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.TextField(blank=True, help_text='TTP5', null=True, verbose_name='MDL5'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='description',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='logo',
            field=models.OneToOneField(blank=True, help_text='TTP11', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Image', verbose_name='MDL11'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='name',
            field=models.CharField(help_text='TTP3', max_length=100, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='name_en',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='name_pt_br',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='proficiency',
            field=models.PositiveIntegerField(help_text='TTP10', verbose_name='MDL10'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='site',
            field=models.URLField(blank=True, help_text='TTP9', null=True, verbose_name='MDL9'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='database',
            field=models.ManyToManyField(blank=True, help_text='TTP18', to='portfolio.Databases', verbose_name='MDL18'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='framework',
            field=models.ManyToManyField(blank=True, help_text='TTP17', to='portfolio.Frameworks', verbose_name='MDL17'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='TTP20', to='portfolio.Image', verbose_name='MDL20'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(help_text='TTP3', max_length=100, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name_en',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name_pt_br',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='programming_language',
            field=models.ManyToManyField(help_text='TTP1', to='portfolio.ProgrammingLanguages', verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='technology',
            field=models.ManyToManyField(blank=True, help_text='TTP19', to='portfolio.Technologies', verbose_name='MDL19'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.ForeignKey(help_text='TTP15', on_delete=django.db.models.deletion.CASCADE, to='portfolio.ProjectTypes', verbose_name='MDL15'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='webserver',
            field=models.ManyToManyField(blank=True, help_text='TTP20', to='portfolio.WebServers', verbose_name='MDL20'),
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='description',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='name',
            field=models.CharField(help_text='TTP3', max_length=100, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='name_en',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='name_pt_br',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='en_title',
            field=models.CharField(help_text='MDL31', max_length=100, null=True, verbose_name='MDL31'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='end_year',
            field=models.PositiveIntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016, help_text='TTP29', verbose_name='MDL29'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(help_text='TTP3', max_length=100, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name_en',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name_pt_br',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_year',
            field=models.PositiveIntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016, help_text='TTP27', verbose_name='MDL27'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(help_text='MDL30', max_length=100, null=True, verbose_name='MDL30'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('ED', 'MDL22'), ('XP', 'MDL23'), ('AW', 'MDL24')], default='ED', help_text='TTP25', max_length=2, verbose_name='MDL25'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='where',
            field=models.TextField(help_text='MDL32', verbose_name='MDL32'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tag',
            field=models.CharField(help_text='TTP32', max_length=20, unique=True, verbose_name='MDL32'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='value',
            field=models.TextField(help_text='TTP34', verbose_name='MDL34'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='value_en',
            field=models.TextField(help_text='TTP34', null=True, verbose_name='MDL34'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='value_pt_br',
            field=models.TextField(help_text='TTP34', null=True, verbose_name='MDL34'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='description',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='logo',
            field=models.OneToOneField(blank=True, help_text='TTP11', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Image', verbose_name='MDL11'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='name',
            field=models.CharField(help_text='TTP3', max_length=100, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='name_en',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='name_pt_br',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='proficiency',
            field=models.PositiveIntegerField(help_text='TTP10', verbose_name='MDL10'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='site',
            field=models.URLField(blank=True, help_text='TTP9', null=True, verbose_name='MDL9'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='type',
            field=models.ForeignKey(help_text='TTP14', on_delete=django.db.models.deletion.CASCADE, to='portfolio.TechnologyTypes', verbose_name='MDL14'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2'),
        ),
        migrations.AlterField(
            model_name='technologytypes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='technologytypes',
            name='description',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='technologytypes',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='technologytypes',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='technologytypes',
            name='logo',
            field=models.OneToOneField(blank=True, help_text='TTP11', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Image', verbose_name='MDL11'),
        ),
        migrations.AlterField(
            model_name='technologytypes',
            name='name',
            field=models.CharField(help_text='TTP3', max_length=100, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='technologytypes',
            name='name_en',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='technologytypes',
            name='name_pt_br',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='technologytypes',
            name='proficiency',
            field=models.PositiveIntegerField(help_text='TTP10', verbose_name='MDL10'),
        ),
        migrations.AlterField(
            model_name='technologytypes',
            name='site',
            field=models.URLField(blank=True, help_text='TTP9', null=True, verbose_name='MDL9'),
        ),
        migrations.AlterField(
            model_name='technologytypes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='auxiliary_tag',
            field=models.CharField(help_text='TTP32', max_length=20, verbose_name='ToolTipTag'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='auxiliary_text',
            field=models.TextField(help_text='TTP34', verbose_name='ToolTipText'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='auxiliary_text_en',
            field=models.TextField(help_text='TTP34', null=True, verbose_name='ToolTipText'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='auxiliary_text_pt_br',
            field=models.TextField(help_text='TTP34', null=True, verbose_name='ToolTipText'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='tag',
            field=models.CharField(help_text='TTP32', max_length=20, unique=True, verbose_name='MDL32'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text',
            field=models.TextField(help_text='TTP34', verbose_name='MDL34'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text_en',
            field=models.TextField(help_text='TTP34', null=True, verbose_name='MDL34'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text_pt_br',
            field=models.TextField(help_text='TTP34', null=True, verbose_name='MDL34'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='type',
            field=models.ForeignKey(help_text='TTP33', on_delete=django.db.models.deletion.CASCADE, related_name='translation_translation_type', to='portfolio.TranslationType', verbose_name='MDL33'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2'),
        ),
        migrations.AlterField(
            model_name='translationtype',
            name='auxiliary_tag',
            field=models.CharField(help_text='TTP32', max_length=20, unique=True, verbose_name='MDL32'),
        ),
        migrations.AlterField(
            model_name='translationtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='translationtype',
            name='name',
            field=models.TextField(help_text='TTP34', verbose_name='MDL34'),
        ),
        migrations.AlterField(
            model_name='translationtype',
            name='name_en',
            field=models.TextField(help_text='TTP34', null=True, verbose_name='MDL34'),
        ),
        migrations.AlterField(
            model_name='translationtype',
            name='name_pt_br',
            field=models.TextField(help_text='TTP34', null=True, verbose_name='MDL34'),
        ),
        migrations.AlterField(
            model_name='translationtype',
            name='tag',
            field=models.CharField(help_text='TTP32', max_length=20, unique=True, verbose_name='MDL32'),
        ),
        migrations.AlterField(
            model_name='translationtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2'),
        ),
        migrations.AlterField(
            model_name='webservers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1'),
        ),
        migrations.AlterField(
            model_name='webservers',
            name='description',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='webservers',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='webservers',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AlterField(
            model_name='webservers',
            name='logo',
            field=models.OneToOneField(blank=True, help_text='TTP11', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.Image', verbose_name='MDL11'),
        ),
        migrations.AlterField(
            model_name='webservers',
            name='name',
            field=models.CharField(help_text='TTP3', max_length=100, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='webservers',
            name='name_en',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='webservers',
            name='name_pt_br',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AlterField(
            model_name='webservers',
            name='proficiency',
            field=models.PositiveIntegerField(help_text='TTP10', verbose_name='MDL10'),
        ),
        migrations.AlterField(
            model_name='webservers',
            name='site',
            field=models.URLField(blank=True, help_text='TTP9', null=True, verbose_name='MDL9'),
        ),
        migrations.AlterField(
            model_name='webservers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2'),
        ),
    ]
