# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20160801_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationtype',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='translationtype',
            old_name='text_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='translationtype',
            old_name='text_pt_br',
            new_name='name_pt_br',
        ),
        migrations.AddField(
            model_name='translation',
            name='tooltip_text_en',
            field=models.TextField(help_text='TTP034', null=True, verbose_name='ToolTipText'),
        ),
        migrations.AddField(
            model_name='translation',
            name='tooltip_text_pt_br',
            field=models.TextField(help_text='TTP034', null=True, verbose_name='ToolTipText'),
        ),
    ]
