# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 21:34
from __future__ import unicode_literals

from django.db import migrations


def load_data(apps, schema_editor):
    translation = apps.get_model("portfolio", "Translation")
    translation(tag='TTP001', type='TTP', text_en="Data da criação do registro",
                text_pt_br="Date of the record creation").save()
    translation(tag='TTP002', type='TTP', text_en="Data da atualização do registro",
                text_pt_br="Date of the record update").save()
    translation(tag='TTP003', type='TTP', text_en="Nome do registro", text_pt_br="Record name").save()
    translation(tag='TTP004', type='TTP', text_en="Descrição do Registro", text_pt_br="Record descriptio").save()
    translation(tag='TTP005', type='TTP', text_en="Título da imagem", text_pt_br="Image title").save()
    translation(tag='TTP006', type='TTP', text_en="Dado Binário da Imagem", text_pt_br="Image binary data").save()
    translation(tag='TTP007', type='TTP', text_en="Tipo do arquivo", text_pt_br="Image type").save()
    translation(tag='TTP008', type='TTP', text_en="Extensão da imagem", text_pt_br="Image extension").save()
    translation(tag='MTP001', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP002', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='TTP009', type='TTP', text_en="Site", text_pt_br="Site").save()
    translation(tag='TTP010', type='TTP', text_en="Proeficiência", text_pt_br="Proficiency").save()
    translation(tag='TTP011', type='TTP', text_en="Logo", text_pt_br="Logo").save()
    translation(tag='MTP003', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP004', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP005', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP006', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='TTP012', type='TTP', text_en="Linguagem de programação do framework",
                text_pt_br="Framework's programming language").save()
    translation(tag='MTP007', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP008', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='TTP013', type='TTP', text_en="Se a base de dados é do tipo SQL",
                text_pt_br="If the database is SQL").save()
    translation(tag='MTP009', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP010', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP011', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP012', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP013', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP014', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='TTP014', type='TTP', text_en="Tipo de tecnologia", text_pt_br="Tipo de tecnologia").save()
    translation(tag='MTP015', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP016', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='TTP015', type='TTP', text_en="Tipo de projeto", text_pt_br="Tipo de projeto").save()
    translation(tag='TTP016', type='TTP', text_en="Linguagens de programação utilizadas",
                text_pt_br="Programming languages used in the project").save()
    translation(tag='TTP017', type='TTP', text_en="Frameworks utilizados no projeto",
                text_pt_br="Frameworks used in the project").save()
    translation(tag='TTP018', type='TTP', text_en="Bases de dados utilizadas no projeto",
                text_pt_br="Databases used in the project").save()
    translation(tag='TTP019', type='TTP', text_en="Tecnologias utilizadas no projeto",
                text_pt_br="Technologies used in the project").save()
    translation(tag='TTP020', type='TTP', text_en="Servidores web utilizados no projeto",
                text_pt_br="Webservers used in the project").save()
    translation(tag='TTP021', type='TTP', text_en="Imagens do projeto", text_pt_br="Project's images").save()
    translation(tag='MTP017', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP018', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='TTP022', type='TTP', text_en="Educação", text_pt_br="Education").save()
    translation(tag='TTP023', type='TTP', text_en="Experiência", text_pt_br="Experience").save()
    translation(tag='TTP024', type='TTP', text_en="Prêmios", text_pt_br="Awards").save()
    translation(tag='TTP025', type='TTP', text_en="Tipo de experiência", text_pt_br="Experience type").save()
    translation(tag='TTP026', type='TTP', text_en="Mês de início", text_pt_br="Start month").save()
    translation(tag='TTP027', type='TTP', text_en="Ano de início", text_pt_br="Start year").save()
    translation(tag='TTP028', type='TTP', text_en="Mês de término", text_pt_br="End month").save()
    translation(tag='TTP029', type='TTP', text_en="Ano de término", text_pt_br="End year").save()
    translation(tag='TTP030', type='TTP', text_en="Cargo", text_pt_br="Title").save()
    translation(tag='TTP031', type='TTP', text_en="Localização", text_pt_br="Location").save()
    translation(tag='MTP019', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP020', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='MTP021', type='MTP', text_en="-", text_pt_br="-").save()
    translation(tag='TTP032', type='TTP', text_en="-", text_pt_br="-").save()
    translation(tag='TTP033', type='TTP', text_en="-", text_pt_br="-").save()
    translation(tag='TTP034', type='TTP', text_en="-", text_pt_br="-").save()
    translation(tag='TTP035', type='TTP', text_en="-", text_pt_br="-").save()
    translation(tag='TTP036', type='TTP', text_en="-", text_pt_br="-").save()
    translation(tag='TTP037', type='TTP', text_en="-", text_pt_br="-").save()
    translation(tag='TTP038', type='TTP', text_en="-", text_pt_br="-").save()
    translation(tag='MDL001', type='MDL', text_en="Data de criação", text_pt_br="Creation date").save()
    translation(tag='MDL002', type='MDL', text_en="Data de atualização", text_pt_br="Update date").save()
    translation(tag='MDL003', type='MDL', text_en="Nome", text_pt_br="Name").save()
    translation(tag='MDL004', type='MDL', text_en="Descrição", text_pt_br="Description").save()
    translation(tag='MDL005', type='MDL', text_en="Título", text_pt_br="Title").save()
    translation(tag='MDL006', type='MDL', text_en="Dado binário", text_pt_br="Binary data").save()
    translation(tag='MDL007', type='MDL', text_en="Tipo MIME", text_pt_br="MIME type").save()
    translation(tag='MDL008', type='MDL', text_en="Extensão", text_pt_br="Extension").save()
    translation(tag='MTA001', type='MTA', text_en="Imagem", text_pt_br="Image").save()
    translation(tag='MTA002', type='MTA', text_en="Imagens", text_pt_br="Images").save()
    translation(tag='MDL009', type='MDL', text_en="Site", text_pt_br="Site").save()
    translation(tag='MDL010', type='MDL', text_en="Proeficiência", text_pt_br="Proficiency").save()
    translation(tag='MDL011', type='MDL', text_en="Logo", text_pt_br="Logo").save()
    translation(tag='MTA003', type='MTA', text_en="Linguagem de programação",
                text_pt_br="Linguagens de programação").save()
    translation(tag='MTA004', type='MTA', text_en="Programming language", text_pt_br="Programming languages").save()
    translation(tag='MTA005', type='MTA', text_en="Framework", text_pt_br="Framework").save()
    translation(tag='MTA006', type='MTA', text_en="Frameworks", text_pt_br="Frameworks").save()
    translation(tag='MDL012', type='MDL', text_en="Linguagem de programação do framework",
                text_pt_br="Framework's programming language").save()
    translation(tag='MTA007', type='MTA', text_en="Base de dados", text_pt_br="Database").save()
    translation(tag='MTA008', type='MTA', text_en="Bases de dados", text_pt_br="Databases").save()
    translation(tag='MDL013', type='MDL', text_en="SQL", text_pt_br="SQL").save()
    translation(tag='MTA009', type='MTA', text_en="Servidor web", text_pt_br="Webserver").save()
    translation(tag='MTA010', type='MTA', text_en="Servidores web", text_pt_br="Webservers").save()
    translation(tag='MTA011', type='MTA', text_en="Tipo de tecnologia", text_pt_br="Technology type").save()
    translation(tag='MTA012', type='MTA', text_en="Tipos de tecnologia", text_pt_br="Technology types").save()
    translation(tag='MTA013', type='MTA', text_en="Tecnologia", text_pt_br="Technology").save()
    translation(tag='MTA014', type='MTA', text_en="Tecnologias", text_pt_br="Technologies").save()
    translation(tag='MDL014', type='MDL', text_en="Tipo de tecnologia", text_pt_br="Technology type").save()
    translation(tag='MTA015', type='MTA', text_en="Tipo de projeto", text_pt_br="Project type").save()
    translation(tag='MTA016', type='MTA', text_en="Tipos de projeto", text_pt_br="Projects types").save()
    translation(tag='MDL015', type='MDL', text_en="Tipo de projeto", text_pt_br="Project type").save()
    translation(tag='MDL016', type='MDL', text_en="Linguagem de programação utilizada",
                text_pt_br="Programming language used").save()
    translation(tag='MDL017', type='MDL', text_en="Frameworks utilizado", text_pt_br="Framework used").save()
    translation(tag='MDL018', type='MDL', text_en="Base de dados utilizada", text_pt_br="Database used").save()
    translation(tag='MDL019', type='MDL', text_en="Tecnologia utilizada", text_pt_br="Technology used").save()
    translation(tag='MDL020', type='MDL', text_en="Servidor web utilizado", text_pt_br="Webserver used").save()
    translation(tag='MDL021', type='MDL', text_en="Imagens do projeto", text_pt_br="Project's images").save()
    translation(tag='MTA017', type='MTA', text_en="Projeto", text_pt_br="Project").save()
    translation(tag='MTA018', type='MTA', text_en="Projetos", text_pt_br="Projects").save()
    translation(tag='MDL022', type='MDL', text_en="Educação", text_pt_br="Education").save()
    translation(tag='MDL023', type='MDL', text_en="Experiência", text_pt_br="Experience").save()
    translation(tag='MDL024', type='MDL', text_en="Prêmios", text_pt_br="Awards").save()
    translation(tag='MDL025', type='MDL', text_en="Tipo de experiência", text_pt_br="Experience type").save()
    translation(tag='MDL026', type='MDL', text_en="Mês de início", text_pt_br="Start month").save()
    translation(tag='MDL027', type='MDL', text_en="Ano de início", text_pt_br="Start year").save()
    translation(tag='MDL028', type='MDL', text_en="Mês de término", text_pt_br="End month").save()
    translation(tag='MDL029', type='MDL', text_en="Ano de término", text_pt_br="End year").save()
    translation(tag='MDL030', type='MDL', text_en="Cargo", text_pt_br="Title").save()
    translation(tag='MDL031', type='MDL', text_en="Localização", text_pt_br="Location").save()
    translation(tag='MTA019', type='MTA', text_en="Currículo", text_pt_br="Resume").save()
    translation(tag='MTA020', type='MTA', text_en="Tradução", text_pt_br="Translation").save()
    translation(tag='MTA021', type='MTA', text_en="Traduções", text_pt_br="Translations").save()
    translation(tag='MDL032', type='MDL', text_en="tag", text_pt_br="tag").save()
    translation(tag='MDL033', type='MDL', text_en="Tipo", text_pt_br="type").save()
    translation(tag='MDL034', type='MDL', text_en="Texto", text_pt_br="Text").save()
    translation(tag='MDL035', type='MDL', text_en="Ajuda de modelo", text_pt_br="Model tooltip").save()
    translation(tag='MDL036', type='MDL', text_en="Modelo", text_pt_br="Model").save()
    translation(tag='MDL037', type='MDL', text_en="Meta", text_pt_br="Meta").save()
    translation(tag='MDL038', type='MDL', text_en="Ajuda de meta", text_pt_br="Meta tooltip").save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20160716_2133'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
