# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 21:34
from __future__ import unicode_literals

from django.db import migrations


def load_data(apps, schema_editor):
    translation = apps.get_model("portfolio", "Translation")
    translation(tag='TTP001', type='TTP', text_pt_br="Data da criação do registro",
                text_en="Date of the record creation").save()
    translation(tag='TTP002', type='TTP', text_pt_br="Data da atualização do registro",
                text_en="Date of the record update").save()
    translation(tag='TTP003', type='TTP', text_pt_br="Nome do registro", text_en="Record name").save()
    translation(tag='TTP004', type='TTP', text_pt_br="Descrição do Registro", text_en="Record descriptio").save()
    translation(tag='TTP005', type='TTP', text_pt_br="Título da imagem", text_en="Image title").save()
    translation(tag='TTP006', type='TTP', text_pt_br="Dado Binário da Imagem", text_en="Image binary data").save()
    translation(tag='TTP007', type='TTP', text_pt_br="Tipo do arquivo", text_en="Image type").save()
    translation(tag='TTP008', type='TTP', text_pt_br="Extensão da imagem", text_en="Image extension").save()
    translation(tag='MTP001', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP002', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='TTP009', type='TTP', text_pt_br="Site", text_en="Site").save()
    translation(tag='TTP010', type='TTP', text_pt_br="Proeficiência", text_en="Proficiency").save()
    translation(tag='TTP011', type='TTP', text_pt_br="Logo", text_en="Logo").save()
    translation(tag='MTP003', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP004', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP005', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP006', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='TTP012', type='TTP', text_pt_br="Linguagem de programação do framework",
                text_en="Framework's programming language").save()
    translation(tag='MTP007', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP008', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='TTP013', type='TTP', text_pt_br="Se a base de dados é do tipo SQL",
                text_en="If the database is SQL").save()
    translation(tag='MTP009', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP010', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP011', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP012', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP013', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP014', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='TTP014', type='TTP', text_pt_br="Tipo de tecnologia", text_en="Tipo de tecnologia").save()
    translation(tag='MTP015', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP016', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='TTP015', type='TTP', text_pt_br="Tipo de projeto", text_en="Tipo de projeto").save()
    translation(tag='TTP016', type='TTP', text_pt_br="Linguagens de programação utilizadas",
                text_en="Programming languages used in the project").save()
    translation(tag='TTP017', type='TTP', text_pt_br="Frameworks utilizados no projeto",
                text_en="Frameworks used in the project").save()
    translation(tag='TTP018', type='TTP', text_pt_br="Bases de dados utilizadas no projeto",
                text_en="Databases used in the project").save()
    translation(tag='TTP019', type='TTP', text_pt_br="Tecnologias utilizadas no projeto",
                text_en="Technologies used in the project").save()
    translation(tag='TTP020', type='TTP', text_pt_br="Servidores web utilizados no projeto",
                text_en="Webservers used in the project").save()
    translation(tag='TTP021', type='TTP', text_pt_br="Imagens do projeto", text_en="Project's images").save()
    translation(tag='MTP017', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP018', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='TTP022', type='TTP', text_pt_br="Educação", text_en="Education").save()
    translation(tag='TTP023', type='TTP', text_pt_br="Experiência", text_en="Experience").save()
    translation(tag='TTP024', type='TTP', text_pt_br="Prêmios", text_en="Awards").save()
    translation(tag='TTP025', type='TTP', text_pt_br="Tipo de experiência", text_en="Experience type").save()
    translation(tag='TTP026', type='TTP', text_pt_br="Mês de início", text_en="Start month").save()
    translation(tag='TTP027', type='TTP', text_pt_br="Ano de início", text_en="Start year").save()
    translation(tag='TTP028', type='TTP', text_pt_br="Mês de término", text_en="End month").save()
    translation(tag='TTP029', type='TTP', text_pt_br="Ano de término", text_en="End year").save()
    translation(tag='TTP030', type='TTP', text_pt_br="Cargo", text_en="Title").save()
    translation(tag='TTP031', type='TTP', text_pt_br="Localização", text_en="Location").save()
    translation(tag='MTP019', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP020', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='MTP021', type='MTP', text_pt_br="-", text_en="-").save()
    translation(tag='TTP032', type='TTP', text_pt_br="-", text_en="-").save()
    translation(tag='TTP033', type='TTP', text_pt_br="-", text_en="-").save()
    translation(tag='TTP034', type='TTP', text_pt_br="-", text_en="-").save()
    translation(tag='TTP035', type='TTP', text_pt_br="-", text_en="-").save()
    translation(tag='TTP036', type='TTP', text_pt_br="-", text_en="-").save()
    translation(tag='TTP037', type='TTP', text_pt_br="-", text_en="-").save()
    translation(tag='TTP038', type='TTP', text_pt_br="-", text_en="-").save()
    translation(tag='MDL001', type='MDL', text_pt_br="Data de criação", text_en="Creation date").save()
    translation(tag='MDL002', type='MDL', text_pt_br="Data de atualização", text_en="Update date").save()
    translation(tag='MDL003', type='MDL', text_pt_br="Nome", text_en="Name").save()
    translation(tag='MDL004', type='MDL', text_pt_br="Descrição", text_en="Description").save()
    translation(tag='MDL005', type='MDL', text_pt_br="Título", text_en="Title").save()
    translation(tag='MDL006', type='MDL', text_pt_br="Dado binário", text_en="Binary data").save()
    translation(tag='MDL007', type='MDL', text_pt_br="Tipo MIME", text_en="MIME type").save()
    translation(tag='MDL008', type='MDL', text_pt_br="Extensão", text_en="Extension").save()
    translation(tag='MTA001', type='MTA', text_pt_br="Imagem", text_en="Image").save()
    translation(tag='MTA002', type='MTA', text_pt_br="Imagens", text_en="Images").save()
    translation(tag='MDL009', type='MDL', text_pt_br="Site", text_en="Site").save()
    translation(tag='MDL010', type='MDL', text_pt_br="Proeficiência", text_en="Proficiency").save()
    translation(tag='MDL011', type='MDL', text_pt_br="Logo", text_en="Logo").save()
    translation(tag='MTA003', type='MTA', text_pt_br="Linguagem de programação",
                text_en="Linguagens de programação").save()
    translation(tag='MTA004', type='MTA', text_pt_br="Linguagens de programação", text_en="Programming languages").save()
    translation(tag='MTA005', type='MTA', text_pt_br="Framework", text_en="Framework").save()
    translation(tag='MTA006', type='MTA', text_pt_br="Frameworks", text_en="Frameworks").save()
    translation(tag='MDL012', type='MDL', text_pt_br="Linguagem de programação do framework",
                text_en="Framework's programming language").save()
    translation(tag='MTA007', type='MTA', text_pt_br="Base de dados", text_en="Database").save()
    translation(tag='MTA008', type='MTA', text_pt_br="Bases de dados", text_en="Databases").save()
    translation(tag='MDL013', type='MDL', text_pt_br="SQL", text_en="SQL").save()
    translation(tag='MTA009', type='MTA', text_pt_br="Servidor web", text_en="Webserver").save()
    translation(tag='MTA010', type='MTA', text_pt_br="Servidores web", text_en="Webservers").save()
    translation(tag='MTA011', type='MTA', text_pt_br="Tipo de tecnologia", text_en="Technology type").save()
    translation(tag='MTA012', type='MTA', text_pt_br="Tipos de tecnologia", text_en="Technology types").save()
    translation(tag='MTA013', type='MTA', text_pt_br="Tecnologia", text_en="Technology").save()
    translation(tag='MTA014', type='MTA', text_pt_br="Tecnologias", text_en="Technologies").save()
    translation(tag='MDL014', type='MDL', text_pt_br="Tipo de tecnologia", text_en="Technology type").save()
    translation(tag='MTA015', type='MTA', text_pt_br="Tipo de projeto", text_en="Project type").save()
    translation(tag='MTA016', type='MTA', text_pt_br="Tipos de projeto", text_en="Projects types").save()
    translation(tag='MDL015', type='MDL', text_pt_br="Tipo de projeto", text_en="Project type").save()
    translation(tag='MDL016', type='MDL', text_pt_br="Linguagem de programação utilizada",
                text_en="Programming language used").save()
    translation(tag='MDL017', type='MDL', text_pt_br="Frameworks utilizado", text_en="Framework used").save()
    translation(tag='MDL018', type='MDL', text_pt_br="Base de dados utilizada", text_en="Database used").save()
    translation(tag='MDL019', type='MDL', text_pt_br="Tecnologia utilizada", text_en="Technology used").save()
    translation(tag='MDL020', type='MDL', text_pt_br="Servidor web utilizado", text_en="Webserver used").save()
    translation(tag='MDL021', type='MDL', text_pt_br="Imagens do projeto", text_en="Project's images").save()
    translation(tag='MTA017', type='MTA', text_pt_br="Projeto", text_en="Project").save()
    translation(tag='MTA018', type='MTA', text_pt_br="Projetos", text_en="Projects").save()
    translation(tag='MDL022', type='MDL', text_pt_br="Educação", text_en="Education").save()
    translation(tag='MDL023', type='MDL', text_pt_br="Experiência", text_en="Experience").save()
    translation(tag='MDL024', type='MDL', text_pt_br="Prêmios", text_en="Awards").save()
    translation(tag='MDL025', type='MDL', text_pt_br="Tipo de experiência", text_en="Experience type").save()
    translation(tag='MDL026', type='MDL', text_pt_br="Mês de início", text_en="Start month").save()
    translation(tag='MDL027', type='MDL', text_pt_br="Ano de início", text_en="Start year").save()
    translation(tag='MDL028', type='MDL', text_pt_br="Mês de término", text_en="End month").save()
    translation(tag='MDL029', type='MDL', text_pt_br="Ano de término", text_en="End year").save()
    translation(tag='MDL030', type='MDL', text_pt_br="Cargo", text_en="Title").save()
    translation(tag='MDL031', type='MDL', text_pt_br="Localização", text_en="Location").save()
    translation(tag='MTA019', type='MTA', text_pt_br="Currículo", text_en="Resume").save()
    translation(tag='MTA020', type='MTA', text_pt_br="Tradução", text_en="Translation").save()
    translation(tag='MTA021', type='MTA', text_pt_br="Traduções", text_en="Translations").save()
    translation(tag='MDL032', type='MDL', text_pt_br="tag", text_en="tag").save()
    translation(tag='MDL033', type='MDL', text_pt_br="Tipo", text_en="type").save()
    translation(tag='MDL034', type='MDL', text_pt_br="Texto", text_en="Text").save()
    translation(tag='MDL035', type='MDL', text_pt_br="Ajuda de modelo", text_en="Model tooltip").save()
    translation(tag='MDL036', type='MDL', text_pt_br="Modelo", text_en="Model").save()
    translation(tag='MDL037', type='MDL', text_pt_br="Meta", text_en="Meta").save()
    translation(tag='MDL038', type='MDL', text_pt_br="Ajuda de meta", text_en="Meta tooltip").save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20160716_2133'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
