# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 16:50:37
from __future__ import unicode_literals

from django.db import migrations


def __load_data(**kwargs):
    apps = kwargs.pop('apps', None)
    translation_type = apps.get_model("portfolio", "TranslationType")
    if apps:
        model = apps.get_model("portfolio", "Translation")
        try:
            mdl = model.objects.get(tag=kwargs['tag'])
        except model.DoesNotExist:
            mdl = model()
        except Exception as err:
            raise err
        for k, v in kwargs.items():
            if k == "type":
                setattr(mdl, k, translation_type.objects.get(tag=v))
            else:
                setattr(mdl, k, v)
        setattr(mdl, "migration_created", True)
        mdl.save()


def clear_data(apps, schema_editor):
    model = apps.get_model("portfolio", "Translation")
    model.objects.all().delete()


def load_data(apps, schema_editor):
    __load_data(apps=apps, tag="MDL1", type="MDL - Model", text_pt_br="Data de criação", text_en="Creation date",auxiliary_tag="TTP1", auxiliary_text_pt_br="Data da criação do registro", auxiliary_text_en="Date of the record creation")
    __load_data(apps=apps, tag="MDL2", type="MDL - Model", text_pt_br="Data de atualização", text_en="Update date",auxiliary_tag="TTP2", auxiliary_text_pt_br="Data da atualização do registro", auxiliary_text_en="Date of the record update")
    __load_data(apps=apps, tag="MDL3", type="MDL - Model", text_pt_br="Nome", text_en="Name",auxiliary_tag="TTP3", auxiliary_text_pt_br="Nome do registro", auxiliary_text_en="Record name")
    __load_data(apps=apps, tag="MDL4", type="MDL - Model", text_pt_br="Descrição", text_en="Description",auxiliary_tag="TTP4", auxiliary_text_pt_br="Descrição do Registro", auxiliary_text_en="Record description")
    __load_data(apps=apps, tag="MDL5", type="MDL - Model", text_pt_br="Título", text_en="Title",auxiliary_tag="TTP5", auxiliary_text_pt_br="Título da imagem", auxiliary_text_en="Image title")
    __load_data(apps=apps, tag="MDL6", type="MDL - Model", text_pt_br="Dado binário", text_en="Binary data",auxiliary_tag="TTP6", auxiliary_text_pt_br="Dado Binário da Imagem", auxiliary_text_en="Image binary data")
    __load_data(apps=apps, tag="MDL7", type="MDL - Model", text_pt_br="Tipo MIME", text_en="MIME type",auxiliary_tag="TTP7", auxiliary_text_pt_br="Tipo do arquivo", auxiliary_text_en="Image type")
    __load_data(apps=apps, tag="MDL8", type="MDL - Model", text_pt_br="Extensão", text_en="Extension",auxiliary_tag="TTP8", auxiliary_text_pt_br="Extensão da imagem", auxiliary_text_en="Image extension")
    __load_data(apps=apps, tag="MDL9", type="MDL - Model", text_pt_br="Site", text_en="Site",auxiliary_tag="TTP9", auxiliary_text_pt_br="Site", auxiliary_text_en="Site")
    __load_data(apps=apps, tag="MDL10", type="MDL - Model", text_pt_br="Proeficiência", text_en="Proficiency",auxiliary_tag="TTP10", auxiliary_text_pt_br="Proeficiência", auxiliary_text_en="Proficiency")
    __load_data(apps=apps, tag="MDL32", type="MDL - Model", text_pt_br="tag", text_en="tag",auxiliary_tag="TTP32", auxiliary_text_pt_br="-", auxiliary_text_en="-")
    __load_data(apps=apps, tag="MDL11", type="MDL - Model", text_pt_br="Logo", text_en="Logo",auxiliary_tag="TTP11", auxiliary_text_pt_br="Logo", auxiliary_text_en="Logo")
    __load_data(apps=apps, tag="MDL12", type="MDL - Model", text_pt_br="Linguagem de programação do framework", text_en="Framework's programming language",auxiliary_tag="TTP12", auxiliary_text_pt_br="Linguagem de programação do framework", auxiliary_text_en="Framework's programming language")
    __load_data(apps=apps, tag="MDL13", type="MDL - Model", text_pt_br="SQL", text_en="SQL",auxiliary_tag="TTP13", auxiliary_text_pt_br="Se a base de dados é do tipo SQL", auxiliary_text_en="If the database is SQL")
    __load_data(apps=apps, tag="MDL14", type="MDL - Model", text_pt_br="Tipo de tecnologia", text_en="Technology type",auxiliary_tag="TTP14", auxiliary_text_pt_br="Tipo de tecnologia", auxiliary_text_en="Tipo de tecnologia")
    __load_data(apps=apps, tag="MDL15", type="MDL - Model", text_pt_br="Tipo de projeto", text_en="Project type",auxiliary_tag="TTP15", auxiliary_text_pt_br="Tipo de projeto", auxiliary_text_en="Tipo de projeto")
    __load_data(apps=apps, tag="MDL16", type="MDL - Model", text_pt_br="Linguagem de programação utilizada", text_en="Programming language used",auxiliary_tag="TTP16", auxiliary_text_pt_br="Linguagens de programação utilizadas", auxiliary_text_en="Programming languages used in the project")
    __load_data(apps=apps, tag="MDL17", type="MDL - Model", text_pt_br="Frameworks utilizado", text_en="Framework used",auxiliary_tag="TTP17", auxiliary_text_pt_br="Frameworks utilizados no projeto", auxiliary_text_en="Frameworks used in the project")
    __load_data(apps=apps, tag="MDL18", type="MDL - Model", text_pt_br="Base de dados utilizada", text_en="Database used",auxiliary_tag="TTP18", auxiliary_text_pt_br="Bases de dados utilizadas no projeto", auxiliary_text_en="Databases used in the project")
    __load_data(apps=apps, tag="MDL19", type="MDL - Model", text_pt_br="Tecnologia utilizada", text_en="Technology used",auxiliary_tag="TTP19", auxiliary_text_pt_br="Tecnologias utilizadas no projeto", auxiliary_text_en="Technologies used in the project")
    __load_data(apps=apps, tag="MDL20", type="MDL - Model", text_pt_br="Servidor web utilizado", text_en="Webserver used",auxiliary_tag="TTP20", auxiliary_text_pt_br="Servidores web utilizados no projeto", auxiliary_text_en="Webservers used in the project")
    __load_data(apps=apps, tag="MDL21", type="MDL - Model", text_pt_br="Imagens do projeto", text_en="Project's images",auxiliary_tag="TTP21", auxiliary_text_pt_br="Imagens do projeto", auxiliary_text_en="Project's images")
    __load_data(apps=apps, tag="MDL22", type="MDL - Model", text_pt_br="Educação", text_en="Education",auxiliary_tag="TTP22", auxiliary_text_pt_br="Educação", auxiliary_text_en="Education")
    __load_data(apps=apps, tag="MDL23", type="MDL - Model", text_pt_br="Experiência", text_en="Experience",auxiliary_tag="TTP23", auxiliary_text_pt_br="Experiência", auxiliary_text_en="Experience")
    __load_data(apps=apps, tag="MDL24", type="MDL - Model", text_pt_br="Prêmios", text_en="Awards",auxiliary_tag="TTP24", auxiliary_text_pt_br="Prêmios", auxiliary_text_en="Awards")
    __load_data(apps=apps, tag="MDL25", type="MDL - Model", text_pt_br="Tipo de experiência", text_en="Experience type",auxiliary_tag="TTP25", auxiliary_text_pt_br="Tipo de experiência", auxiliary_text_en="Experience type")
    __load_data(apps=apps, tag="MDL26", type="MDL - Model", text_pt_br="Mês de início", text_en="Start month",auxiliary_tag="TTP26", auxiliary_text_pt_br="Mês de início", auxiliary_text_en="Start month")
    __load_data(apps=apps, tag="MDL27", type="MDL - Model", text_pt_br="Ano de início", text_en="Start year",auxiliary_tag="TTP27", auxiliary_text_pt_br="Ano de início", auxiliary_text_en="Start year")
    __load_data(apps=apps, tag="MDL28", type="MDL - Model", text_pt_br="Mês de término", text_en="End month",auxiliary_tag="TTP28", auxiliary_text_pt_br="Mês de término", auxiliary_text_en="End month")
    __load_data(apps=apps, tag="MDL29", type="MDL - Model", text_pt_br="Ano de término", text_en="End year",auxiliary_tag="TTP29", auxiliary_text_pt_br="Ano de término", auxiliary_text_en="End year")
    __load_data(apps=apps, tag="MDL30", type="MDL - Model", text_pt_br="Cargo", text_en="Title",auxiliary_tag="TTP30", auxiliary_text_pt_br="Cargo", auxiliary_text_en="Title")
    __load_data(apps=apps, tag="MDL31", type="MDL - Model", text_pt_br="Localização", text_en="Location",auxiliary_tag="TTP31", auxiliary_text_pt_br="Localização", auxiliary_text_en="Location")
    __load_data(apps=apps, tag="MDL33", type="MDL - Model", text_pt_br="Tipo", text_en="type",auxiliary_tag="TTP33", auxiliary_text_pt_br="-", auxiliary_text_en="-")
    __load_data(apps=apps, tag="MDL34", type="MDL - Model", text_pt_br="Texto", text_en="Text",auxiliary_tag="TTP34", auxiliary_text_pt_br="-", auxiliary_text_en="-")
    __load_data(apps=apps, tag="MDL35", type="MDL - Model", text_pt_br="Ajuda de modelo", text_en="Model tooltip",auxiliary_tag="TTP35", auxiliary_text_pt_br="-", auxiliary_text_en="-")
    __load_data(apps=apps, tag="MDL36", type="MDL - Model", text_pt_br="Modelo", text_en="Model",auxiliary_tag="TTP36", auxiliary_text_pt_br="-", auxiliary_text_en="-")
    __load_data(apps=apps, tag="MDL37", type="MDL - Model", text_pt_br="Meta", text_en="Meta",auxiliary_tag="TTP37", auxiliary_text_pt_br="-", auxiliary_text_en="-")
    __load_data(apps=apps, tag="MDL38", type="MDL - Model", text_pt_br="Ajuda de meta", text_en="Meta tooltip",auxiliary_tag="TTP38", auxiliary_text_pt_br="-", auxiliary_text_en="-")
    __load_data(apps=apps, tag="MTA1", type="MTA - Meta", text_pt_br="Imagem", text_en="Image",auxiliary_tag="MTP1", auxiliary_text_pt_br="Imagens", auxiliary_text_en="Images")
    __load_data(apps=apps, tag="MTA2", type="MTA - Meta", text_pt_br="Linguagem de programação", text_en="Programming language",auxiliary_tag="MTP2", auxiliary_text_pt_br="Linguagens de programação", auxiliary_text_en="Programming languages")
    __load_data(apps=apps, tag="MTA3", type="MTA - Meta", text_pt_br="Framework", text_en="Framework",auxiliary_tag="MTP3", auxiliary_text_pt_br="Frameworks", auxiliary_text_en="Frameworks")
    __load_data(apps=apps, tag="MTA4", type="MTA - Meta", text_pt_br="Base de dados", text_en="Database",auxiliary_tag="MTP4", auxiliary_text_pt_br="Bases de dados", auxiliary_text_en="Databases")
    __load_data(apps=apps, tag="MTA5", type="MTA - Meta", text_pt_br="Servidor web", text_en="Webserver",auxiliary_tag="MTP5", auxiliary_text_pt_br="Servidores web", auxiliary_text_en="Webservers")
    __load_data(apps=apps, tag="MTA6", type="MTA - Meta", text_pt_br="Tipo de tecnologia", text_en="Technology type",auxiliary_tag="MTP6", auxiliary_text_pt_br="Tipos de tecnologia", auxiliary_text_en="Technology types")
    __load_data(apps=apps, tag="MTA7", type="MTA - Meta", text_pt_br="Tecnologia", text_en="Technology",auxiliary_tag="MTP7", auxiliary_text_pt_br="Tecnologias", auxiliary_text_en="Technologies")
    __load_data(apps=apps, tag="MTA8", type="MTA - Meta", text_pt_br="Tipo de projeto", text_en="Project type",auxiliary_tag="MTP8", auxiliary_text_pt_br="Tipos de projeto", auxiliary_text_en="Project types")
    __load_data(apps=apps, tag="MTA9", type="MTA - Meta", text_pt_br="Projeto", text_en="Project",auxiliary_tag="MTP9", auxiliary_text_pt_br="Projetos", auxiliary_text_en="Projects")
    __load_data(apps=apps, tag="MTA10", type="MTA - Meta", text_pt_br="Currículo", text_en="Resume",auxiliary_tag="MTP10", auxiliary_text_pt_br="Currículo", auxiliary_text_en="Resume")
    __load_data(apps=apps, tag="MTA11", type="MTA - Meta", text_pt_br="Tradução", text_en="Translation",auxiliary_tag="MTP11", auxiliary_text_pt_br="Traduções", auxiliary_text_en="Translations")
    __load_data(apps=apps, tag="MTA12", type="MTA - Meta", text_pt_br="Tipo de Tradução", text_en="Translation Type",auxiliary_tag="MTP12", auxiliary_text_pt_br="Tipos de Tradução", auxiliary_text_en="Translation Types")
    __load_data(apps=apps, tag="MTA13", type="MTA - Meta", text_pt_br="Configuração do site", text_en="Site settings",auxiliary_tag="MTP13", auxiliary_text_pt_br="Configurações do site", auxiliary_text_en="Site settings")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20160903_1624'),
    ]

    operations = [
        migrations.RunPython(load_data, clear_data)
    ]

        