# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 16:56:06
from __future__ import unicode_literals

from django.db import migrations


def __load_data(**kwargs):
    apps = kwargs.pop('apps', None)
    translation_type = apps.get_model("portfolio", "TranslationType")
    if apps:
        model = apps.get_model("portfolio", "Translation")
        try:
            mdl = model.objects.get(tag=kwargs['tag'])
        except model.DoesNotExist:
            mdl = model()
        except Exception as err:
            raise err
        for k, v in kwargs.items():
            if k == "type":
                setattr(mdl, k, translation_type.objects.get(tag=v))
            else:
                setattr(mdl, k, v)
        setattr(mdl, "migration_created", True)
        mdl.save()


def clear_data(apps, schema_editor):
    model = apps.get_model("portfolio", "Translation")
    model.objects.all().delete()


def load_data(apps, schema_editor):
    __load_data(apps=apps, tag="GEN2", type="GEN", text_pt_br="desenvolvedor", text_en="developer", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN4", type="GEN", text_pt_br="currículo", text_en="resume", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN6", type="GEN", text_pt_br="projetos", text_en="projects", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN8", type="GEN", text_pt_br="objetivo", text_en="objective", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN10", type="GEN", text_pt_br="educação", text_en="education", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN12", type="GEN", text_pt_br="Anos de experiência", text_en="Years of experience", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN14", type="GEN", text_pt_br="Endereço", text_en="Address/Street", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN16", type="GEN", text_pt_br="nome", text_en="name", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN18", type="GEN", text_pt_br="assunto", text_en="subject", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN20", type="GEN", text_pt_br="Enviar mensagem", text_en="Send message", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN3", type="GEN", text_pt_br="sobre", text_en="about", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN5", type="GEN", text_pt_br="habilidades", text_en="skills", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN7", type="GEN", text_pt_br="contato", text_en="contact", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN9", type="GEN", text_pt_br="O que eu faço", text_en="what I do", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN11", type="GEN", text_pt_br="experiência", text_en="experience", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN13", type="GEN", text_pt_br="Projetos concluídos", text_en="Done projects", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN15", type="GEN", text_pt_br="Telefone", text_en="Phone Number", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN17", type="GEN", text_pt_br="email", text_en="email", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN19", type="GEN", text_pt_br="mensagem", text_en="message", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20160903_1624'),
    ]

    operations = [
        migrations.RunPython(load_data, clear_data)
    ]

        