# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_translation_initial_data_20160716_2134'),
    ]

    operations = [
    ]
