# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 17:42:00
from __future__ import unicode_literals

from django.db import migrations


def __load_data(**kwargs):
    apps = kwargs.pop('apps', None)
    translation_type = apps.get_model("portfolio", "TranslationType")
    if apps:
        model = apps.get_model("portfolio", "Translation")
        try:
            mdl = model.objects.get(tag=kwargs['tag'])
        except model.DoesNotExist:
            mdl = model()
        except Exception as err:
            raise err
        for k, v in kwargs.items():
            if k == "type":
                setattr(mdl, k, translation_type.objects.get(tag=v))
            else:
                setattr(mdl, k, v)
        setattr(mdl, "migration_created", True)
        mdl.save()


def clear_data(apps, schema_editor):
    model = apps.get_model("portfolio", "Translation")
    model.objects.all().delete()


def load_data(apps, schema_editor):
    __load_data(apps=apps, tag="GEN22", type="GEN", text_pt_br="Data de nascimento", text_en="Date of birth", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN24", type="GEN", text_pt_br="Me enviar uma mensagem", text_en="Send me a message", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN26", type="GEN", text_pt_br="Todos", text_en="All", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN21", type="GEN", text_pt_br="Nacionalidade", text_en="Nationality", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN23", type="GEN", text_pt_br="Baixe meu currículo", text_en="Download my CV", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN25", type="GEN", text_pt_br="Tudo", text_en="All", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20160905_1656'),
    ]

    operations = [
        migrations.RunPython(load_data, clear_data)
    ]

        