# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 12:20:07
from __future__ import unicode_literals

from django.db import migrations


def __load_data(**kwargs):
    apps = kwargs.pop('apps', None)
    translation_type = apps.get_model("portfolio", "TranslationType")
    if apps:
        model = apps.get_model("portfolio", "Translation")
        try:
            mdl = model.objects.get(tag=kwargs['tag'])
        except model.DoesNotExist:
            mdl = model()
        except Exception as err:
            raise err
        for k, v in kwargs.items():
            if k == "type":
                setattr(mdl, k, translation_type.objects.get(tag=v))
            else:
                setattr(mdl, k, v)
        setattr(mdl, "migration_created", True)
        mdl.save()


def clear_data(apps, schema_editor):
    model = apps.get_model("portfolio", "Translation")
    model.objects.filter(tag__in=["MTA14"]).delete()


def load_data(apps, schema_editor):
    __load_data(apps=apps, tag="MTA14", type="MTA", text_pt_br="Habilidade", text_en="Skill", auxiliary_tag="MTP14", auxiliary_text_pt_br="Habilidades", auxiliary_text_en="Skills")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20160905_1742'),
    ]

    operations = [
        migrations.RunPython(load_data, clear_data)
    ]

        