# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20160721_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP004', null=True, verbose_name='MDL004'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='name_en',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='name_pt_br',
            field=models.CharField(help_text='TTP003', max_length=100, null=True, verbose_name='MDL003'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value_en',
            field=models.TextField(help_text='TTP034', null=True, verbose_name='MDL034'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value_pt_br',
            field=models.TextField(help_text='TTP034', null=True, verbose_name='MDL034'),
        ),
    ]
