# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20160721_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='description_pt_br',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='name_pt_br',
        ),
    ]
