# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20160906_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2')),
                ('name', models.CharField(help_text='TTP3', max_length=100, verbose_name='MDL3')),
                ('description', models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4')),
            ],
            options={
                'verbose_name_plural': 'MTP14',
                'verbose_name': 'MTA14',
            },
        ),
    ]
