# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='TTP4', null=True, verbose_name='MDL4'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_pt_br',
            field=models.CharField(help_text='TTP3', max_length=100, null=True, verbose_name='MDL3'),
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(default=0, help_text='TTP10', verbose_name='MDL10'),
            preserve_default=False,
        ),
    ]
