# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 13:00:27
from __future__ import unicode_literals

from django.db import migrations


def __load_data(**kwargs):
    apps = kwargs.pop('apps', None)
    translation_type = apps.get_model("portfolio", "TranslationType")
    if apps:
        model = apps.get_model("portfolio", "Translation")
        try:
            mdl = model.objects.get(tag=kwargs['tag'])
        except model.DoesNotExist:
            mdl = model()
        except Exception as err:
            raise err
        for k, v in kwargs.items():
            if k == "type":
                setattr(mdl, k, translation_type.objects.get(tag=v))
            else:
                setattr(mdl, k, v)
        setattr(mdl, "migration_created", True)
        mdl.save()


def clear_data(apps, schema_editor):
    model = apps.get_model("portfolio", "Translation")
    model.objects.filter(tag__in=["GEN29","GEN17","GEN28"]).delete()


def load_data(apps, schema_editor):
    __load_data(apps=apps, tag="GEN29", type="GEN", text_pt_br="TEste21", text_en="Teste21", auxiliary_tag="", auxiliary_text_pt_br="", auxiliary_text_en="")
    __load_data(apps=apps, tag="GEN17", type="GEN", text_pt_br="Email", text_en="Email", auxiliary_tag="", auxiliary_text_pt_br="None", auxiliary_text_en="None")
    __load_data(apps=apps, tag="GEN28", type="GEN", text_pt_br="TESTE", text_en="TESTE", auxiliary_tag="", auxiliary_text_pt_br="", auxiliary_text_en="")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20160906_1234'),
    ]

    operations = [
        migrations.RunPython(load_data, clear_data)
    ]

        