# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20160906_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'MDL39'), ('gauge', 'MDL40')], default='bar', help_text='TTP41', max_length=45, verbose_name='MDL41'),
            preserve_default=False,
        ),
    ]
