# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 14:54:41
from __future__ import unicode_literals

from django.db import migrations


def __load_data(**kwargs):
    apps = kwargs.pop('apps', None)
    translation_type = apps.get_model("portfolio", "TranslationType")
    if apps:
        model = apps.get_model("portfolio", "Translation")
        try:
            mdl = model.objects.get(tag=kwargs['tag'])
        except model.DoesNotExist:
            mdl = model()
        except Exception as err:
            raise err
        for k, v in kwargs.items():
            if k == "type":
                setattr(mdl, k, translation_type.objects.get(tag=v))
            else:
                setattr(mdl, k, v)
        setattr(mdl, "migration_created", True)
        mdl.save()


def clear_data(apps, schema_editor):
    model = apps.get_model("portfolio", "Translation")
    model.objects.filter(tag__in=["MDL10"]).delete()


def load_data(apps, schema_editor):
    __load_data(apps=apps, tag="MDL10", type="MDL", text_pt_br="Proeficiência", text_en="Proficiency", auxiliary_tag="TTP10", auxiliary_text_pt_br="Proeficiência - inteiro, de 0 a 100", auxiliary_text_en="Proficiency - integer from 0 to 100")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_skill_chart_type'),
    ]

    operations = [
        migrations.RunPython(load_data, clear_data)
    ]

        