# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 15:15:36
from __future__ import unicode_literals

from django.db import migrations


def __load_data(**kwargs):
    apps = kwargs.pop('apps', None)
    translation_type = apps.get_model("portfolio", "TranslationType")
    if apps:
        model = apps.get_model("portfolio", "Translation")
        try:
            mdl = model.objects.get(tag=kwargs['tag'])
        except model.DoesNotExist:
            mdl = model()
        except Exception as err:
            raise err
        for k, v in kwargs.items():
            if k == "type":
                setattr(mdl, k, translation_type.objects.get(tag=v))
            else:
                setattr(mdl, k, v)
        setattr(mdl, "migration_created", True)
        mdl.save()


def clear_data(apps, schema_editor):
    model = apps.get_model("portfolio", "Translation")
    model.objects.filter(tag__in=["MDL42","MTA15","MDL43"]).delete()


def load_data(apps, schema_editor):
    __load_data(apps=apps, tag="MDL42", type="MDL", text_pt_br="Tag auxiliar", text_en="Auxiliary Tag", auxiliary_tag="TTP42", auxiliary_text_pt_br="Tag do texto auxiliar", auxiliary_text_en="Auxiliary text tag")
    __load_data(apps=apps, tag="MTA15", type="MTA", text_pt_br="Palavra chave", text_en="Keyword", auxiliary_tag="MTP15", auxiliary_text_pt_br="Palavras chave", auxiliary_text_en="Keywords")
    __load_data(apps=apps, tag="MDL43", type="MDL", text_pt_br="Texto auxiliar", text_en="Auxiliary text", auxiliary_tag="TTP43", auxiliary_text_pt_br="Texto auxiliar", auxiliary_text_en="Auxiliary text")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20160906_1515'),
    ]

    operations = [
        migrations.RunPython(load_data, clear_data)
    ]

        