# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20160906_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'MTA15', 'verbose_name_plural': 'MTP15'},
        ),
        migrations.AlterField(
            model_name='image',
            name='extension',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_string',
            field=models.TextField(verbose_name='MDL50'),
        ),
        migrations.AlterField(
            model_name='image',
            name='mimetype',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='MDL49'),
        ),
    ]
