# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20160906_1551'),
        ('portfolio', '0019_auto_20160906_1652'),
    ]

    operations = [
    ]
