# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 18:21:07
from __future__ import unicode_literals

from django.db import migrations


def __load_data(**kwargs):
    apps = kwargs.pop('apps', None)
    translation_type = apps.get_model("portfolio", "TranslationType")
    if apps:
        model = apps.get_model("portfolio", "Translation")
        try:
            mdl = model.objects.get(tag=kwargs['tag'])
        except model.DoesNotExist:
            mdl = model()
        except Exception as err:
            raise err
        for k, v in kwargs.items():
            if k == "type":
                setattr(mdl, k, translation_type.objects.get(tag=v))
            else:
                setattr(mdl, k, v)
        setattr(mdl, "migration_created", True)
        mdl.save()


def clear_data(apps, schema_editor):
    model = apps.get_model("portfolio", "Translation")
    model.objects.filter(tag__in=["GEN33","MDL44","GEN32"]).delete()


def load_data(apps, schema_editor):
    __load_data(apps=apps, tag="GEN33", type="GEN", text_pt_br="Novo", text_en="New", auxiliary_tag="", auxiliary_text_pt_br="", auxiliary_text_en="")
    __load_data(apps=apps, tag="MDL44", type="MDL", text_pt_br="Imagem", text_en="Image", auxiliary_tag="TTP44", auxiliary_text_pt_br="Imagem", auxiliary_text_en="Image")
    __load_data(apps=apps, tag="GEN32", type="GEN", text_pt_br="Upload", text_en="Upload", auxiliary_tag="", auxiliary_text_pt_br="", auxiliary_text_en="")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_merge'),
    ]

    operations = [
        migrations.RunPython(load_data, clear_data)
    ]

        