# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 23:15:06
from __future__ import unicode_literals

from django.db import migrations


def __load_data(**kwargs):
    apps = kwargs.pop('apps', None)
    translation_type = apps.get_model("portfolio", "TranslationType")
    if apps:
        model = apps.get_model("portfolio", "Translation")
        try:
            mdl = model.objects.get(tag=kwargs['tag'])
        except model.DoesNotExist:
            mdl = model()
        except Exception as err:
            raise err
        for k, v in kwargs.items():
            if k == "type":
                setattr(mdl, k, translation_type.objects.get(tag=v))
            else:
                setattr(mdl, k, v)
        setattr(mdl, "migration_created", True)
        mdl.save()


def clear_data(apps, schema_editor):
    model = apps.get_model("portfolio", "Translation")
    model.objects.filter(tag__in=["GEN34","GEN35","ME6","ME7"]).delete()


def load_data(apps, schema_editor):
    __load_data(apps=apps, tag="GEN34", type="GEN", text_pt_br="Estou disponível para um projeto como freelancer", text_en="I'm available for freelance project", auxiliary_tag="", auxiliary_text_pt_br="", auxiliary_text_en="")
    __load_data(apps=apps, tag="GEN35", type="GEN", text_pt_br="Entre em contato", text_en="Contact-me", auxiliary_tag="", auxiliary_text_pt_br="", auxiliary_text_en="")
    __load_data(apps=apps, tag="ME6", type="ME", text_pt_br="Houve um erro ao processar sua requisição, por favor tente novamente mais tarde", text_en="There was an error processing your request, please try again later", auxiliary_tag="", auxiliary_text_pt_br="", auxiliary_text_en="")
    __load_data(apps=apps, tag="ME7", type="ME", text_pt_br="Email enviado com sucesso", text_en="Email sent successfully", auxiliary_tag="", auxiliary_text_pt_br="", auxiliary_text_en="")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_auto_20160914_2214'),
    ]

    operations = [
        migrations.RunPython(load_data, clear_data)
    ]

        