# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_auto_20160921_2315'),
        ('portfolio', '0024_auto_20160914_2214'),
    ]

    operations = [
    ]
